### ISSUE TITLE
Ambiguous language words are transcribed as foreign in newest version

### ISSUE THREAD

**Issue by G-Thor** [grammatek/iceprondict#4]
Words such as 'burt' 'small' and 'sein' are transcribed incorrectly in the pronunciation dictionary.
They are transcribed as follows:
burt	p 9 r_0 t
sein	s ai: n
small	s m O l

This is not desired behaviour. In ambiguous cases, we probably usually want the Icelandic pronunciation. 
These are just the ones I came across, there may very well be more.

This kind of issue can be avoided by having a separate lexicon "addendum" with loan words and other foreign words. Doing so would also enable more stable g2p model training, as we dont want a model transcribing new 'pure Icelandic' compound words, neologisms etc. to be confused by e.g. English loan-word phonology.

It might also be a good idea to separate out acronyms, single characters and other NSWs

**Comment by G-Thor** [comment]
To prevent confusion, I might add that the correct Icelandic pronunciation of the words I listed is (if I am not mistaken) as follows:
burt p Y r_0 t
sein s ei: n
small s m a t l_0

**Comment by bnika** [comment]
I'll have a look at how it happens that such words are not in their Icelandic version in the  dictionary. As for the second point: the complete versions of the dictionaries are labeled with language, e.g. to be able to sort them out for training of models. The simple dictionaries are extracted from the complete versions.

**Comment by bnika** [comment]
Homograph entries in the complete-dictionary (like 'small', 'burt' 'sein'): when extracting the dialect dictionaries, now always the Icelandic pronunciation is chosen
